#include "atomic.h"

#include <stddef.h>

#define LOAD(SUB, TYPE, WIDTH, ALIGN) \
    { (SUB), TURBOWASM_ATOMIC_LOAD, TURBOWASM_ATOMIC_OP_NONE, \
      (TYPE), (WIDTH), (ALIGN) }

#define STORE(SUB, TYPE, WIDTH, ALIGN) \
    { (SUB), TURBOWASM_ATOMIC_STORE, TURBOWASM_ATOMIC_OP_NONE, \
      (TYPE), (WIDTH), (ALIGN) }

#define RMW(SUB, OP, TYPE, WIDTH, ALIGN) \
    { (SUB), TURBOWASM_ATOMIC_RMW, (OP), \
      (TYPE), (WIDTH), (ALIGN) }

#define CMPXCHG(SUB, TYPE, WIDTH, ALIGN) \
    { (SUB), TURBOWASM_ATOMIC_CMPXCHG, TURBOWASM_ATOMIC_OP_NONE, \
      (TYPE), (WIDTH), (ALIGN) }

static const turbowasm_atomic_descriptor descriptors[] = {
    LOAD(0x10u, TURBOWASM_ATOMIC_I32, 4u, 2u),
    LOAD(0x11u, TURBOWASM_ATOMIC_I64, 8u, 3u),
    LOAD(0x12u, TURBOWASM_ATOMIC_I32, 1u, 0u),
    LOAD(0x13u, TURBOWASM_ATOMIC_I32, 2u, 1u),
    LOAD(0x14u, TURBOWASM_ATOMIC_I64, 1u, 0u),
    LOAD(0x15u, TURBOWASM_ATOMIC_I64, 2u, 1u),
    LOAD(0x16u, TURBOWASM_ATOMIC_I64, 4u, 2u),

    STORE(0x17u, TURBOWASM_ATOMIC_I32, 4u, 2u),
    STORE(0x18u, TURBOWASM_ATOMIC_I64, 8u, 3u),
    STORE(0x19u, TURBOWASM_ATOMIC_I32, 1u, 0u),
    STORE(0x1au, TURBOWASM_ATOMIC_I32, 2u, 1u),
    STORE(0x1bu, TURBOWASM_ATOMIC_I64, 1u, 0u),
    STORE(0x1cu, TURBOWASM_ATOMIC_I64, 2u, 1u),
    STORE(0x1du, TURBOWASM_ATOMIC_I64, 4u, 2u),

    RMW(0x1eu, TURBOWASM_ATOMIC_OP_ADD, TURBOWASM_ATOMIC_I32, 4u, 2u),
    RMW(0x1fu, TURBOWASM_ATOMIC_OP_ADD, TURBOWASM_ATOMIC_I64, 8u, 3u),
    RMW(0x20u, TURBOWASM_ATOMIC_OP_ADD, TURBOWASM_ATOMIC_I32, 1u, 0u),
    RMW(0x21u, TURBOWASM_ATOMIC_OP_ADD, TURBOWASM_ATOMIC_I32, 2u, 1u),
    RMW(0x22u, TURBOWASM_ATOMIC_OP_ADD, TURBOWASM_ATOMIC_I64, 1u, 0u),
    RMW(0x23u, TURBOWASM_ATOMIC_OP_ADD, TURBOWASM_ATOMIC_I64, 2u, 1u),
    RMW(0x24u, TURBOWASM_ATOMIC_OP_ADD, TURBOWASM_ATOMIC_I64, 4u, 2u),

    RMW(0x25u, TURBOWASM_ATOMIC_OP_SUB, TURBOWASM_ATOMIC_I32, 4u, 2u),
    RMW(0x26u, TURBOWASM_ATOMIC_OP_SUB, TURBOWASM_ATOMIC_I64, 8u, 3u),
    RMW(0x27u, TURBOWASM_ATOMIC_OP_SUB, TURBOWASM_ATOMIC_I32, 1u, 0u),
    RMW(0x28u, TURBOWASM_ATOMIC_OP_SUB, TURBOWASM_ATOMIC_I32, 2u, 1u),
    RMW(0x29u, TURBOWASM_ATOMIC_OP_SUB, TURBOWASM_ATOMIC_I64, 1u, 0u),
    RMW(0x2au, TURBOWASM_ATOMIC_OP_SUB, TURBOWASM_ATOMIC_I64, 2u, 1u),
    RMW(0x2bu, TURBOWASM_ATOMIC_OP_SUB, TURBOWASM_ATOMIC_I64, 4u, 2u),

    RMW(0x2cu, TURBOWASM_ATOMIC_OP_AND, TURBOWASM_ATOMIC_I32, 4u, 2u),
    RMW(0x2du, TURBOWASM_ATOMIC_OP_AND, TURBOWASM_ATOMIC_I64, 8u, 3u),
    RMW(0x2eu, TURBOWASM_ATOMIC_OP_AND, TURBOWASM_ATOMIC_I32, 1u, 0u),
    RMW(0x2fu, TURBOWASM_ATOMIC_OP_AND, TURBOWASM_ATOMIC_I32, 2u, 1u),
    RMW(0x30u, TURBOWASM_ATOMIC_OP_AND, TURBOWASM_ATOMIC_I64, 1u, 0u),
    RMW(0x31u, TURBOWASM_ATOMIC_OP_AND, TURBOWASM_ATOMIC_I64, 2u, 1u),
    RMW(0x32u, TURBOWASM_ATOMIC_OP_AND, TURBOWASM_ATOMIC_I64, 4u, 2u),

    RMW(0x33u, TURBOWASM_ATOMIC_OP_OR, TURBOWASM_ATOMIC_I32, 4u, 2u),
    RMW(0x34u, TURBOWASM_ATOMIC_OP_OR, TURBOWASM_ATOMIC_I64, 8u, 3u),
    RMW(0x35u, TURBOWASM_ATOMIC_OP_OR, TURBOWASM_ATOMIC_I32, 1u, 0u),
    RMW(0x36u, TURBOWASM_ATOMIC_OP_OR, TURBOWASM_ATOMIC_I32, 2u, 1u),
    RMW(0x37u, TURBOWASM_ATOMIC_OP_OR, TURBOWASM_ATOMIC_I64, 1u, 0u),
    RMW(0x38u, TURBOWASM_ATOMIC_OP_OR, TURBOWASM_ATOMIC_I64, 2u, 1u),
    RMW(0x39u, TURBOWASM_ATOMIC_OP_OR, TURBOWASM_ATOMIC_I64, 4u, 2u),

    RMW(0x3au, TURBOWASM_ATOMIC_OP_XOR, TURBOWASM_ATOMIC_I32, 4u, 2u),
    RMW(0x3bu, TURBOWASM_ATOMIC_OP_XOR, TURBOWASM_ATOMIC_I64, 8u, 3u),
    RMW(0x3cu, TURBOWASM_ATOMIC_OP_XOR, TURBOWASM_ATOMIC_I32, 1u, 0u),
    RMW(0x3du, TURBOWASM_ATOMIC_OP_XOR, TURBOWASM_ATOMIC_I32, 2u, 1u),
    RMW(0x3eu, TURBOWASM_ATOMIC_OP_XOR, TURBOWASM_ATOMIC_I64, 1u, 0u),
    RMW(0x3fu, TURBOWASM_ATOMIC_OP_XOR, TURBOWASM_ATOMIC_I64, 2u, 1u),
    RMW(0x40u, TURBOWASM_ATOMIC_OP_XOR, TURBOWASM_ATOMIC_I64, 4u, 2u),

    RMW(0x41u, TURBOWASM_ATOMIC_OP_XCHG, TURBOWASM_ATOMIC_I32, 4u, 2u),
    RMW(0x42u, TURBOWASM_ATOMIC_OP_XCHG, TURBOWASM_ATOMIC_I64, 8u, 3u),
    RMW(0x43u, TURBOWASM_ATOMIC_OP_XCHG, TURBOWASM_ATOMIC_I32, 1u, 0u),
    RMW(0x44u, TURBOWASM_ATOMIC_OP_XCHG, TURBOWASM_ATOMIC_I32, 2u, 1u),
    RMW(0x45u, TURBOWASM_ATOMIC_OP_XCHG, TURBOWASM_ATOMIC_I64, 1u, 0u),
    RMW(0x46u, TURBOWASM_ATOMIC_OP_XCHG, TURBOWASM_ATOMIC_I64, 2u, 1u),
    RMW(0x47u, TURBOWASM_ATOMIC_OP_XCHG, TURBOWASM_ATOMIC_I64, 4u, 2u),

    CMPXCHG(0x48u, TURBOWASM_ATOMIC_I32, 4u, 2u),
    CMPXCHG(0x49u, TURBOWASM_ATOMIC_I64, 8u, 3u),
    CMPXCHG(0x4au, TURBOWASM_ATOMIC_I32, 1u, 0u),
    CMPXCHG(0x4bu, TURBOWASM_ATOMIC_I32, 2u, 1u),
    CMPXCHG(0x4cu, TURBOWASM_ATOMIC_I64, 1u, 0u),
    CMPXCHG(0x4du, TURBOWASM_ATOMIC_I64, 2u, 1u),
    CMPXCHG(0x4eu, TURBOWASM_ATOMIC_I64, 4u, 2u)
};

_Static_assert(
    sizeof(descriptors) / sizeof(descriptors[0]) ==
        (0x4eu - 0x10u + 1u),
    "atomic descriptor table must cover 0x10..0x4e");

const turbowasm_atomic_descriptor *
turbowasm_atomic_descriptor_find(uint32_t subopcode) {
    if (subopcode < 0x10u || subopcode > 0x4eu)
        return NULL;
    return &descriptors[subopcode - 0x10u];
}
